package TextpressoDatabaseCategories;

# Package contains categories that should be displayed.
# (c) 2007 Hans-Michael Muller, Caltech, Pasadena.

require Exporter;
our @ISA = qw(Exporter);
our @EXPORT = qw(DB_CATEGORIES DB_CATEGORYCHILDREN DB_SUPERCATEGORIES);

use strict;


use constant DB_SUPERCATEGORIES => {
  'Concepts' => [ 'amino acid',
		  'anatomy',
		  'artificial satellite',
		  'biological concept',
		  'celestial entity',
		  'chemical element',
		  'cloud',
		  'discharge',
		  'earth atmosphere',
		  'electromagnetic radiation',
		  'emission',
		  'environment',
		  'feature',
		  'gas',
		  'growth',
		  'hydrogen compound',
		  'organic compound',
		  'particle',
		  'research equipment',
		  'rock',
		  'scientific discipline',
		  'soil'],
  'Descriptions' => [  'action' ,   'characterization',  'coordinates',
  'decomposition',
  'defect', 
  'descriptor',  'effect',  'electrical properties',
  'electromagnetic properties',  'localization',  'measurement',  'phase',
  'phase transformation',  'property',
  'purpose',],
  'Relationships' => [  'association', 'chemical reaction',  'comparison',
  'consort',  'involvement',  'spatial relation',  'time relation',]
};
use constant DB_CATEGORIES => {
    'action' => 'action',
    'amino acid' => 'aminoacid',
    'anatomy' => 'anatomy',
    'artificial satellite' => 'artificialsatellite',
    'association' => 'association',
    'asteroid' => 'asteroid',
    'bacteria' => 'bacteria',
    'biological entity feature' => 'bioentityfeature',
    'biological process' => 'biologicalprocess',
    'cabohydrate' => 'carbohydrate',
    'celestial entity' => 'celestialentity',
    'cell' => 'cell',
    'characterization' => 'characterization',
    'chemical element' => 'chemicalelement',
    'chemical reaction' => 'chemicalreaction',
    'cloud' => 'cloud',
    'comet' => 'comet',
    'comparison' => 'comparison',
    'consort' => 'consort',
    'constellation' => 'constellation',
    'coordinates' => 'coordinates',
    'decomposition' => 'decomposition',
    'defect' => 'defect',
    'density' => 'density',
    'descriptor' => 'descriptor',
    'd/h ratio' => 'dhratio',
    'discharge' => 'discharge',
    'earth atmosphere' => 'earthatmosphere',
    'effect' => 'effect',  
    'electrical properties' => 'electricalproperties',
    'electromagnetic properties' => 'electromagneticproperties',
    'electromagnetic radiation' => 'electromagradiation',
    'electron' => 'electron',
    'elementary excitations' => 'elementaryexcitations',
    'elementary particle' => 'elementaryparticle',
    'emission' => 'emission',
    'environment' => 'environment',
    'feature' => 'feature',
    'galaxy' => 'galaxy',
    'gas' => 'gases',
    'growth (GO)' => 'growth',
    'hydrocarbon' => 'hydrocarbon',
    'hydrogen compound' => 'hydrogencompound',
    'interstellar matter' => 'interstellarmatter',
    'interstellar molecule' => 'interstellarmolecule',
    'involvement' => 'involvement',
    'jupiter satellite' => 'jupitersatellite',
    'life' => 'life',
    'localization' => 'localization',
    'magnetically trapped particle' => 'magneticallytrappedpart',
    'mars satellite' => 'marssatellite',
    'measurement' => 'measure',
    'meteorite' => 'meteorite',
    'meteoroid' => 'meteoroid',
    'mixture' => 'mixture',
    'nebula' => 'nebula',
    'neptune satellite' => 'neptunesatellite',
    'nuclei' => 'nuclei',
    'nucleic acid' => 'nucleic_acid',
    'observatory' => 'observatory',
    'organic compound' => 'organiccompound',
    'particle' => 'particle',
    'phase' => 'phase',
    'phase transformation' => 'phasetransformation',
    'planet' => 'planet',
    'plasma' => 'plasma',
    'pluto satellite' => 'plutosatellite',
    'polycyclic aromatic hydrocarbon (PAH)' => 'pah',
    'polycyclic aromatic nitrogen heterocycle (PANH)' => 'panh',
    'property' => 'property',
    'protein' => 'protein',
    'purpose' => 'purpose',
    'radio source' => 'radiosource',
    'rock' => 'rock',
    'saturn satellite' => 'saturnsatellite',
    'scientific discipline' => 'discipline',
    'shape' => 'shape',
    'soil' => 'soil',
    'spatial relation' => 'spatialreln',
    'star' => 'star',
    'telescope' => 'telescope',
    'time relation' => 'timereln',
    'uranus satellite' => 'uranussatellite',
    'volatile' => 'volatile',
    'water' => 'water'
    };
use constant DB_CATEGORYCHILDREN => {
  'biological concept' => [ 'bacteria', 
			    'biological entity feature',
			    'biological process',
			    'cell', 
			    'life'],
    'celestial entity' => ['asteroid', 
				  'comet',
				  'galaxy',
				  'interstellar matter',
				  'interstellar molecule',
				  'jupiter satellite',
				  'mars satellite',
				  'meteorite',
				  'meteoroid',
				  'nebula',
				  'neptune satellite',
				  'planet',
				  'pluto satellite',
				  'radio source',
				  'saturn satellite',
				  'star',
				  'uranus satellite'],
    'hydrogen compound' => ['water'],
    'measurement' => ['density',
				  'd/h ratio'],	
    'organic compound' => ['amino acid',
				  'carbohydrate',
				  'hydrocarbon',
				  'nucleic acid',
				  'polycyclic aromatic hydrocarbon (PAH)',
				  'polycyclic aromatic nitrogen heterocycle (PANH)',
				  'protein',
				  'volatile'
				  ],
    'particle' => ['elementary particle',
				    'electron',
				    'elementary excitations',
				    'magnetically trapped particle',
				    'nuclei',
				    'plasma'],
		    
    'property' => ['density',
				'mixture',
				'shape'],
  'research equipment' => ['observatory',
			   'telescope']
    };
1;
